handle:
  - rewrite:if (!is_file() && !is_dir() && path ~ "^/(.*)") goto "index.html/$1"
  - rewrite: if( in_header["Host"] == "www.sunjd.me" && path ~ "(.*)" ) goto "http://portfoliosjd.sinaapp.com$1?%{QUERY_STRING}"
